server:
  port: 8181
  compression.enabled: true

logging.level:
  org.springframework:
    security: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://cockroachdb.nexr.kr:5432/im?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect

etcd:
  rest.url: http://etcd-api.nexr.kr/v2/keys/
  revision.limit: 20
  http.client.pool.max: 10
